### ISSUE TITLE
Add unit_of_measurement setting

### ISSUE THREAD

**Issue by stast1** [bessarabov/animated-consumption-card#2]
Hello!
Is it possible to add a setting for units of measure, for example in Russian - 'Вт' and 'кВт'?

**Comment by bessarabov** [comment]
Can you please add additional details of what you need.

Do you have a sensor in Home Assistant that has unit `Вт`/`кВт`:
```
sensor:
  - platform: template
    sensors:
      total_power_consumption:
        unit_of_measurement: Вт
        ....
```

Or the sensor in Home Assistant has unit_of_measurement `kWh`/`W`, but you want to this card to display text in russian language in this card?

![Screenshot 2020-05-22 at 11 28 35](https://user-images.githubusercontent.com/47263/82647955-9f5fdb00-9c1f-11ea-991c-54e3e6e2a0c5.png)

If you want to change the text in the card I have one more question. Is is ok if there is no additional settings in the card, but the card just uses the language of Home Assistant interface.
